name: CICD

on:
  push:
    branches: [stage]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u onlinestore1407 -p svitsmachnogo
      - name: Build docker image
        run: docker build -t onlinestore1407/svitsmachnogo .
      - name: Publish image to docker hub
        run: docker push onlinestore1407/svitsmachnogo:latest
  deploy:
    needs: build
    runs-on: [netx]
    steps:
      - name: Go to root catalog
        run: cd
      - name: Delete old docker compose file
        run: sudo rm -f docker-compose.yml
      - name: Download docker compose file
        run: sudo curl -O -L https://github.com/AndriiSpyrydonenko/Onlinestore1407back/raw/stage/docker-compose.yml
      - name: Delete old container
        run: sudo docker rm -f svitsmachnogo-container
      - name: Delete old image
        run: sudo docker image rm -f onlinestore1407/svitsmachnogo:latest
      - name: Run docker container
        run: sudo docker compose up -d


